# Generated by Django 5.0.3 on 2024-07-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image',
        ),
    ]
