# Generated by Django 5.0.3 on 2024-07-20 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_reward_image'),
        ('myapp', '0003_alter_reward_image'),
    ]

    operations = [
    ]
