# Generated by Django 5.1.7 on 2025-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./images/'),
        ),
    ]
